force-app/main/default/objects/Trading_Product__c/Trading_Product__c.object-meta.xml
<CustomObject>
    <description>The enlisted trading cards in the market.</description>
    <label>Trading Product</label>
    <nameField>
        <displayFormat>TP-{00000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trading Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trading_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trading Products</relationshipLabel>
    <relationshipName>Trading_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/byObjects/TradingProduct/TradingProductSelector.cls
public with sharing class TradingProductSelector implements ITradingProductSelector {
  public TradingProductCountingWrapper[] getCountings(
    Set<Id> tradingProductIDs
  ) {
    TradingProductCountingWrapper[] wrappers = new List<TradingProductCountingWrapper>();
    List<AggregateResult> rawResults = [
      SELECT Account__c, count(Id) tradingProductsCount
      FROM Trading_Product__c
      WHERE Id IN :tradingProductIDs
      GROUP BY Account__c
    ];

    for (AggregateResult counting : rawResults) {
      TradingProductCountingWrapper wrapper = new TradingProductCountingWrapper();
      wrapper.AccountID = (Id) counting.get('Account__c');
      wrapper.TradingProductsCount = (Integer) counting.get(
        'tradingProductsCount'
      );
      wrappers.add(wrapper);
    }

    return wrappers;
  }
}