force-app/main/default/objects/Account/fields/Trading_Cards_Count__c.field-meta.xml
<CustomField>
    <fullName>Trading_Cards_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of cards linked to this Account</description>
    <inlineHelpText>Auto-generated</inlineHelpText>
    <label>Trading Cards Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trading_Product__c/Trading_Product__c.object-meta.xml
<CustomObject>
    <description>The enlisted trading cards in the market.</description>
    <label>Trading Product</label>
    <nameField>
        <displayFormat>TP-{00000}</displayFormat>
        <label>No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trading Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trading_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trading Products</relationshipLabel>
    <relationshipName>Trading_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tests/byObjects/TradingProduct/TradingProductHandlerTest.cls
@IsTest
public with sharing class TradingProductHandlerTest {
  static RandomGenerator randomGeneratorInstance = new RandomGenerator();

  static SObjectType ACCOUNT_TYPE = Account.getSObjectType();
  static SObjectType TRADING_PRODUCT_TYPE = Trading_Product__c.getSObjectType();

  @IsTest
  static void whenInsertedWithSameAccount_shouldUpdateAccountTradingProductsCount() {
    // Arrange
    List<Account> accounts = TinyTestWorkshop.buildAccounts(1);
    accounts[0].Id = randomGeneratorInstance.buildId(ACCOUNT_TYPE);

    Integer tradingProductsCount = 3;
    List<Trading_Product__c> tradingProducts = TinyTestWorkshop.buildTradingProducts(
      tradingProductsCount
    );
    List<Id> tradingProductIDs = randomGeneratorInstance.buildId(
      TRADING_PRODUCT_TYPE,
      tradingProductsCount
    );

    for (Integer i = 0; i < tradingProductsCount; i++) {
      tradingProducts[i].Id = tradingProductIDs[i];
      tradingProducts[i].Account__c = accounts[0].Id;
    }

    TradingProductCountingWrapper tradingProductsCountingResult = new TradingProductCountingWrapper();
    tradingProductsCountingResult.AccountID = accounts[0].Id;
    tradingProductsCountingResult.TradingProductsCount = tradingProductsCount;

    // Configure mock SOQL results
    Mock accountSelectorMock = Mock.forType(IAccountSelector.class);
    MethodSpy selectByIDSpy = accountSelectorMock.spyOn('selectByID');
    selectByIDSpy.returns(accounts);

    Mock tradingProductSelectorMock = Mock.forType(
      ITradingProductSelector.class
    );
    MethodSpy getCountingsSpy = tradingProductSelectorMock.spyOn(
      'getCountings'
    );
    getCountingsSpy.returns(
      new List<TradingProductCountingWrapper>{ tradingProductsCountingResult }
    );

    // Configure DML
    Mock dbModifierMock = Mock.forType(IDBModifier.class);
    MethodSpy doUpdateSpy = dbModifierMock.spyOn('doUpdate');

    // Prepare the dependency map
    Map<String, Object> dependencyMap = new Map<String, Object>{
      'IAccountSelector' => accountSelectorMock.stub,
      'ITradingProductSelector' => tradingProductSelectorMock.stub,
      'IDBModifier' => dbModifierMock.stub
    };

    // Act
    Test.startTest();
    TriggerSnip snip = new TriggerSnip().fromList(tradingProducts);
    new TradingProductHandler(dependencyMap).fromSnip(snip).afterInsert();
    Test.stopTest();

    // Verify
    List<Account> updatedAccounts = (List<Account>) MockUtils.getModifiedMockData(
      doUpdateSpy
    );
    Account updatedAccount = updatedAccounts[0];

    Assert.areEqual(
      tradingProductsCount,
      updatedAccount.Trading_Cards_Count__c
    );
  }

  @IsTest
  static void whenInsertedLargeQuantities_shouldUpdateAccountTradingProductsCount() {
    // Arrange
    Integer accountsCount = 100;
    List<Account> accounts = TinyTestWorkshop.buildAccounts(accountsCount);
    List<Id> accountIDs = randomGeneratorInstance.buildId(
      ACCOUNT_TYPE,
      accountsCount
    );

    for (Integer i = 0; i < accountsCount; i++) {
      accounts[i].Id = accountIDs[i];
    }

    Integer tradingProductsCount = 100;
    List<Trading_Product__c> tradingProducts = TinyTestWorkshop.buildTradingProducts(
      tradingProductsCount
    );
    List<Id> tradingProductIDs = randomGeneratorInstance.buildId(
      TRADING_PRODUCT_TYPE,
      tradingProductsCount
    );

    for (Integer i = 0; i < tradingProductsCount; i++) {
      tradingProducts[i].Id = tradingProductIDs[i];
      tradingProducts[i].Account__c = accounts[i].Id;
    }

    TradingProductCountingWrapper[] tradingProductsCountingResults = new List<TradingProductCountingWrapper>();
    for (Integer i = 0; i < accountsCount; i++) {
      TradingProductCountingWrapper countingResult = new TradingProductCountingWrapper();
      countingResult.AccountId = accounts[i].Id;
      countingResult.TradingProductsCount = 1;
      tradingProductsCountingResults.add(countingResult);
    }

    // Configure mock SOQL results
    Mock accountSelectorMock = Mock.forType(IAccountSelector.class);
    MethodSpy selectByIDSpy = accountSelectorMock.spyOn('selectByID');
    selectByIDSpy.returns(accounts);

    Mock tradingProductSelectorMock = Mock.forType(
      ITradingProductSelector.class
    );
    MethodSpy getCountingsSpy = tradingProductSelectorMock.spyOn(
      'getCountings'
    );
    getCountingsSpy.returns(tradingProductsCountingResults);

    // Configure DML
    Mock dbModifierMock = Mock.forType(IDBModifier.class);
    MethodSpy doUpdateSpy = dbModifierMock.spyOn('doUpdate');

    // Prepare the dependency map
    Map<String, Object> dependencyMap = new Map<String, Object>{
      'IAccountSelector' => accountSelectorMock.stub,
      'ITradingProductSelector' => tradingProductSelectorMock.stub,
      'IDBModifier' => dbModifierMock.stub
    };

    // Act
    Test.startTest();
    TriggerSnip snip = new TriggerSnip().fromList(tradingProducts);
    new TradingProductHandler(dependencyMap).fromSnip(snip).afterInsert();
    Test.stopTest();

    // Verify
    List<Account> updatedAccounts = (List<Account>) MockUtils.getModifiedMockData(
      doUpdateSpy
    );

    Account updatedAccount = (Account) updatedAccounts[accountsCount - 1];
    Assert.areEqual(1, updatedAccount.Trading_Cards_Count__c);
  }
}